import { NextResponse } from "next/server";
import { createClient, createServiceClient } from "@/lib/supabase/server";
import { getAnthropicClient } from "@/lib/anthropic/client";
import { MODELS } from "@/lib/anthropic/utils";
import {
  DEAL_COUNTER_SYSTEM,
  buildDealCounterPrompt,
  type DealCounterResult,
} from "@/lib/anthropic/prompts/deal-counter";
import { getRelevantCorpus, formatCorpusForPrompt } from "@/lib/corpus/index";

export async function POST(req: Request) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: profile } = await supabase
    .from("profiles")
    .select("organisation_id")
    .eq("id", user.id)
    .single();
  if (!profile?.organisation_id) return NextResponse.json({ error: "No organisation" }, { status: 403 });

  const body = await req.json() as {
    deal_room_id: string;
    original_term: object;
    jurisdiction?: string;
  };

  if (!body.deal_room_id || !body.original_term) {
    return NextResponse.json({ error: "deal_room_id and original_term required" }, { status: 400 });
  }

  const jurisdiction = body.jurisdiction ?? "IN";

  const corpusEntries = await getRelevantCorpus(["influencer marketing", "brand deals"], jurisdiction);
  const corpusContext = formatCorpusForPrompt(corpusEntries);

  const anthropic = getAnthropicClient();
  const msg = await anthropic.messages.create({
    model: MODELS.SONNET,
    max_tokens: 2000,
    system: DEAL_COUNTER_SYSTEM,
    messages: [{ role: "user", content: buildDealCounterPrompt(body.original_term, corpusContext, jurisdiction) }],
  });

  let result: DealCounterResult = { counter_term: {}, reasoning: "", negotiation_notes: "" };
  try {
    const raw = msg.content[0].type === "text" ? msg.content[0].text : "{}";
    result = JSON.parse(raw) as DealCounterResult;
  } catch { /* keep default */ }

  // Insert counter_proposal message
  const service = await createServiceClient();
  const { data: newMsg } = await service
    .from("deal_messages")
    .insert({
      deal_room_id: body.deal_room_id,
      sender_id: user.id,
      message_type: "counter_proposal",
      content: result.reasoning || "Counter-proposal generated by AI",
      term_json: result.counter_term as unknown as Record<string, unknown>,
    })
    .select()
    .single();

  return NextResponse.json({ ...result, message: newMsg });
}
